AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "Gemfile"
    - "Rakefile"
    - "bin/*"

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Exclude:
    - spec/**/*.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*.rb

Style/ExpandPathArguments:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - spec/**/*.rb
